version: "3.8"
services:

  selenium-server:
    build: ./server
    networks:
      - selenium
    ports:
      - "4444:4444"
    shm_size: 256m
    restart: always

  selenium-client:
    build: ./client
    depends_on:
      - selenium-server
    networks:
      - selenium
    volumes:
      - type: bind
        source: ./client/config.json
        target: /app/config.json
      - type: bind
        source: ./client/images
        target: /app/images
    tty: true
    restart: always

networks:
  selenium:
